version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: product-scanner-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: product-scanner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
